### ISSUE TITLE
crop option does not work

### ISSUE THREAD

**Issue by wilfredonoyola** [uploadcare/react-widget#91]
Hi :),

Problem:

When i added crop:"1:1", I selected a square and it displayed the crop option correctly but then the widget saved the image original to uploadcare services, the widget did not use the options crop i configurated.

Code implemented
`
<Widget
                                                publicKey='djladjfladjflasd'
                                                id='file'
                                                locale = "es"
                                                tabs='file camera'
                                                previewStep='true'
                                                imagesOnly="true"
                                                crop="1:1"
                                                multipleMax="1"
                                                onChange={this.handleChangeUploadedFile}
                                            />
`

Let me know how i will fix it.

Thanks

**Comment by optlsnd** [comment]
Hi @wilfredonoyola 

By design, the widget uploads and stores the original image even if the crop option is enabled. Image cropping is a post-processing operation, and the widget returns a CDN URL of the uploaded image with the "crop" operation added. You can get this URL with the `handleChangeUploadedFile` function. See this article in our docs to learn more about how crop works in the widget
https://uploadcare.com/docs/file_uploads/widget/image_crop/#how-it-works
